### PR TITLE
convert strings to UTF-8 before generating YAML

### PR DESCRIPTION
**Pull request by kevinushey**
This fixes a crash on Windows where attempts to convert latin1 strings could cause a crash.

### CODE REVIEW

**Comment by spgarbet** [comment]
This would help with #105 and #90 but needs to cover all entry points. I'm going to work on extending this.

**Comment by spgarbet** [comment]
Ideally all entry points would use the same function. The as.utf8 is a good fan-in point. The issue now is making sure all entry points use it. R defaults to "unknown" encoding, if it's specified as "latin1" the conversion is straightforward. 

However, what should one assume when the encoding is "unknown"?

I had to add the new util.R file to `makefile` and this results in the following breakage:

`RUNIT TEST PROTOCOL -- Mon Sep 13 11:52:13 2021 
*********************************************** 
Number of test functions: 167 
Number of errors: 1 
Number of failures: 5 

 
1 Test Suite : 
yaml tests - 167 test functions, 1 error, 5 failures
FAILURE in test_custom_tag_for_data_frame: Error in checkEquals(expected, result) : 1 string mismatch

FAILURE in test_custom_tag_for_named_list: Error in checkEquals(expected, result) : 1 string mismatch

FAILURE in test_custom_tag_for_omap: Error in checkEquals(expected, result) : 1 string mismatch

FAILURE in test_custom_tag_for_unnamed_list: Error in checkEquals(expected, result) : 1 string mismatch

ERROR in test_data_frame_is_converted: Error in y[[5]] : subscript out of bounds
FAILURE in test_data_frame_keys_are_escaped_properly_when_row_major: Error in checkEquals("- 'n': 1\n- 'n': 2\n- 'n': 3\n", result) : 
  1 string mismatch

Error in eval(ei, envir) : TEST FAILED!
Calls: source -> withVisible -> eval -> eval
Execution halted
make: *** [Makefile:106: test] Error 1`

**Comment by spgarbet** [comment]
I think the problem in as.utf8 is it drops attributes of an object which are used in conversion.

**Comment by spgarbet** [comment]
I've put everything into a single ticket. There are conflicting needs I'm still trying to figure out the best manner to address.

**Comment by spgarbet** [comment]
@/kevinushey I'm trying to fold in your pull request, the problem is there's a lot of possible R types (outside list/string) and the as.yaml doesn't cover them all. I have looked at the alternative to put the conversion in the C code at the emitter stage, but enc2utf8 is actually do_enc2 in the R library and that's marked as internal only as best I can tell.

**Comment by kevinushey** [comment]
On the R side, you can use `Rf_translateCharUTF8()` to convert a `SEXP` into a UTF-8 string.

**Pull request closed without merging**
