### PR TITLE
Fix non-API calls for closures

### LINKED ISSUE #144: Non-API Calls
R CMD check NOTEs are showing up for the package for R-devel:

https://cran.r-project.org/web/checks/check_results_yaml.html

> File ‘yaml/libs/yaml.so’:
    Found non-API calls to R: ‘SET_BODY’, ‘SET_CLOENV’, ‘SET_FORMALS’
  >
  > Compiled code should not call non-API entry points in R.
  >
 >  See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
  See section ‘Moving into C API compliance’ in the ‘Writing R
  Extensions’ manual for issues with use of non-API entry points.

There is a whole new set of closure-related functions in R4.5.0, and the Writing R Extensions recommendation is to backport these for older R versions: https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Creating-closures

Will provide a PR as I recently fixed this in {nanonext} e.g. at https://github.com/shikokuchuo/nanonext/blob/main/src/aio.c#L25-L33

### PR DESCRIPTION
**Pull request by shikokuchuo**
Fixes #144.

### CODE REVIEW

**Comment by spgarbet** [comment]
Thank you for your contribution. Having a PR makes moving forward a lot faster.

Couple housekeeping things, do you want to add your name to the DESCRIPTION contributor? If you do that can you bump the version number for this change, it's in VERSION and DESCRIPTION. 

Will a new version proposed, the package has strong dependencies and I need to reach out to a couple other groups to get them to run their tests suites and get sign off.

**Comment by spgarbet** [comment]
Tests pass. garbetsp:~/Projects/cran/yaml$ make test
R CMD INSTALL -l build/lib build/yaml
* installing *source* package ‘yaml’ ...
** using staged installation
** libs
using C compiler: ‘gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
make[1]: Entering directory '/home/garbetsp/Projects/cran/yaml/build/yaml/src'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/garbetsp/Projects/cran/yaml/build/yaml/src'
installing to /home/garbetsp/Projects/cran/yaml/build/lib/00LOCK-yaml/00new/yaml/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (yaml)
R --vanilla -e "library(RUnit); library(yaml, lib.loc = 'build/lib'); source('build/yaml/tests/RUnit.R')"

R version 4.4.0 (2024-04-24) -- "Puppy Cup"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(RUnit); library(yaml, lib.loc = 'build/lib'); source('build/yaml/tests/RUnit.R')
RUNIT TEST PROTOCOL -- Wed Jul  3 08:09:21 2024 
*********************************************** 
Number of test functions: 171 
Number of errors: 0 
Number of failures: 0 

 
1 Test Suite : 
yaml tests - 171 test functions, 0 errors, 0 failures
> 
>

**Comment by spgarbet** [comment]
valgrind-test

```
RUNIT TEST PROTOCOL -- Wed Jul  3 08:13:45 2024 
*********************************************** 
Number of test functions: 171 
Number of errors: 0 
Number of failures: 0 

 
1 Test Suite : 
yaml tests - 171 test functions, 0 errors, 0 failures
> 
> 
==1995226== 
==1995226== HEAP SUMMARY:
==1995226==     in use at exit: 57,659,298 bytes in 10,668 blocks
==1995226==   total heap usage: 35,001 allocs, 24,333 frees, 101,535,306 bytes allocated
==1995226== 
==1995226== LEAK SUMMARY:
==1995226==    definitely lost: 0 bytes in 0 blocks
==1995226==    indirectly lost: 0 bytes in 0 blocks
==1995226==      possibly lost: 0 bytes in 0 blocks
==1995226==    still reachable: 57,659,298 bytes in 10,668 blocks
==1995226==                       of which reachable via heuristic:
==1995226==                         newarray           : 4,264 bytes in 1 blocks
==1995226==         suppressed: 0 bytes in 0 blocks
==1995226== Reachable blocks (those to which a pointer was found) are not shown.
==1995226== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==1995226== 
==1995226== For lists of detected and suppressed errors, rerun with: -s
==1995226== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by shikokuchuo** [comment]
> Couple housekeeping things, do you want to add your name to the DESCRIPTION contributor? If you do that can you bump the version number for this change, it's in VERSION and DESCRIPTION.
> 
Sure, I've done that. Separately, I see the GitHub release hasn't caught up to the current CRAN version - that confused me at first.

> Will a new version proposed, the package has strong dependencies and I need to reach out to a couple other groups to get them to run their tests suites and get sign off.

Sure, although this fix shouldn't result in any change in behaviour. Btw. great to see you run Valgrind.

**Comment by spgarbet** [comment]
data.table test with package installed

```
R version 4.4.0 (2024-04-24) -- "Puppy Cup"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> source("~/Projects/cran/data.table/tests/main.R")
Loading required package: data.table
data.table 1.15.4 using 6 threads (see ?getDTthreads).  Latest news: r-datatable.com
getDTthreads(verbose=TRUE):
  OpenMP version (_OPENMP)       201511
  omp_get_num_procs()            12
  R_DATATABLE_NUM_PROCS_PERCENT  unset (default 50)
  R_DATATABLE_NUM_THREADS        unset
  R_DATATABLE_THROTTLE           unset (default 1024)
  omp_get_thread_limit()         2147483647
  omp_get_max_threads()          12
  OMP_THREAD_LIMIT               unset
  OMP_NUM_THREADS                unset
  RestoreAfterFork               true
  data.table is using 6 threads with throttle==1024. See ?setDTthreads.
test.data.table() running: /home/garbetsp/R/x86_64-pc-linux-gnu-library/4.4/data.table/tests/tests.Rraw.bz2

**** Suggested package R.utils is not installed or has dependencies missing. Tests using it will be skipped.

Running test id 2243.56            
Wed Jul  3 09:28:15 2024  endian==little, sizeof(long double)==16, longdouble.digits==64, sizeof(pointer)==8, TZ==unset, Sys.timezone()=='America/Menominee', Sys.getlocale()=='LC_CTYPE=en_US.UTF-8;LC_NUMERIC=C;LC_TIME=en_US.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=en_US.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=en_US.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=en_US.UTF-8;LC_IDENTIFICATION=C', l10n_info()=='MBCS=TRUE; UTF-8=TRUE; Latin-1=FALSE; codeset=UTF-8', getDTthreads()=='OpenMP version (_OPENMP)==201511; omp_get_num_procs()==12; R_DATATABLE_NUM_PROCS_PERCENT==unset (default 50); R_DATATABLE_NUM_THREADS==unset; R_DATATABLE_THROTTLE==unset (default 1024); omp_get_thread_limit()==2147483647; omp_get_max_threads()==12; OMP_THREAD_LIMIT==unset; OMP_NUM_THREADS==unset; RestoreAfterFork==true; data.table is using 6 threads with throttle==1024. See ?setDTthreads.', zlibVersion()==1.2.11 ZLIB_VERSION==1.2.11
10 longest running tests took 13s (47% of 27s)
      ID  time nTest
 1: 2155 3.783     5
 2: 1438 1.807   738
 3: 1437 1.277    36
 4: 1652 1.080    91
 5: 1648 1.051    91
 6: 1223 1.027   728
 7: 1650 0.969    91
 8: 2233 0.891    55
 9: 1252 0.713   484
10: 1642 0.697    91
All 11014 tests (last 2243.56) in tests/tests.Rraw.bz2 completed ok in 31.6s elapsed (36.9s cpu)
> 
```

**Comment by spgarbet** [comment]
@hadley @MichaelChirico Seeking your approval for release of this patch to CRAN.

**Comment by hadley** [comment]
@spgarbet looks fine to me, but I'd feel more confident if you added some GitHub actions to check all relevant versions of R (e.g. with `usethis::use_github_action("check-full")`)

**Comment by spgarbet** [comment]
Our institutions account doesn't cover doing that on github. We do have full gitlab automations. I'm looking into seeing if they have something similar that can be done using gitlab.

**Comment by hadley** [comment]
@spgarbet I don't think that should matter for publicly available repos? IIRC it's only private repos that you need to pay for.

**Comment by spgarbet** [comment]
I set up the github action on the main branch and it's passing.

**Review by spgarbet — APPROVED** [review]
Code change looks good. Hadley has approved if it passes github checks. data.table has not responded, but I ran their test suite and got no errors.

**Comment by MichaelChirico** [comment]
LGTM, thanks for the ping, and thanks @shikokuchuo for the PR :)

**Pull request merged**
